before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: JEJ1nLt/pTeXcFaqcncc+aQNmOlFvocDaU938i5e8MmObk3s7p3cSFZ/cO9s3LRTbndpu2RUoVnwFw7wgVODRDI1XFPMdJBY8so5F5ruaWFVkovRp3BCYgBCCgAqBESUkfxEOKP2xvmKXoqgRZ14BLRk1YCC4r41WJ0XxKzet3iHjkVYf72vVP6iasmvZ5Mg3BiCPtfVI1cN+vr8G0zbzVLonO+UJrIBBsnL6oEWrVDp3kpKlPsTgQVlLsQbFGZsLoEhKx4px58jdTcWQqP07Yz1pLCzxOSfsuQuBKHRVM1JFg/3tlTwVaYBkpAFPBc04MAnHhTuzmXcnCNsb4oE293qUfBJsdGFk9LY2/wstox6tysaOOvSAN5Eo1A129TdYHg1dS1yEOA0wYb+SB4dLfXEZbsn9rRMf1yy8dbtr0L/hk9WuvdbWLBdUVgbJHXUutV0iw6QmDO1hKZSFahthT1hHHeq6kt/zHbX5ZOaDvy+45YKIIqcAzhWp/VfQH621JSCTOHr7ddfVvivIiRTyWDG+a6maM0KSvquMWB7FNThqeL6uUds6yWDFMZ5dDL+I+jaRaac6oEi0Wju4VSqq7XspCIvlj3r6zHBSqUbD6dxfW+6PUw5DVJo7P5FYyQaZchnXzu+jcifEshhqiW2WHRb0Ch0doqWEItXJ+GzRa0= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
